default_language_version:
    python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 21.5b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        exclude: "migrations"
        additional_dependencies: [pep8-naming, flake8-bugbear]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        exclude: "migrations"
