# Generated by Django 3.2.2 on 2022-07-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maas', '0009_add_users_relation_to_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maasoperator',
            name='user',
        ),
    ]
