# Generated by Django 3.2.2 on 2022-07-28 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maas', '0010_remove_user_from_maas_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketingsystem',
            name='users',
            field=models.ManyToManyField(related_name='ticketing_systems', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='transportserviceprovider',
            name='users',
            field=models.ManyToManyField(related_name='tsps', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
