# Generated by Django 3.2.2 on 2022-06-27 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_booking_log_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agency_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='agency name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Time when booking is confirmed', null=True, verbose_name='booking confirmed at'),
        ),
        migrations.AddField(
            model_name='booking',
            name='locale',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish')], default='fi', max_length=2, verbose_name='locale'),
        ),
        migrations.AddField(
            model_name='booking',
            name='route_capacity_sales',
            field=models.CharField(blank=True, max_length=255, verbose_name='Route capacity sales'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('currency_type', models.CharField(help_text='ISO 4217 alphabetical currency code', max_length=3, verbose_name='currency type')),
                ('customer_type_name', models.CharField(blank=True, max_length=255, verbose_name='Customer type name')),
                ('ticket_type_name', models.CharField(blank=True, max_length=255, verbose_name='Ticket type name')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='bookings.booking', verbose_name='booking')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'default_related_name': 'tickets',
            },
        ),
    ]
