name: Build & Staging
on:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STAGING }}
  BASE_DOMAIN: ${{ secrets.BASE_DOMAIN_STAGING }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  APP_MIGRATE_COMMAND: /app/.prod/on_deploy.sh
  K8S_REQUEST_CPU: 50m
  K8S_REQUEST_RAM: 250Mi
  K8S_LIMIT_CPU: 100m
  K8S_LIMIT_RAM: 350Mi
  K8S_REPLICACOUNT: 2

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2

  staging:
    runs-on: ubuntu-latest
    needs: build
    name: Staging
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'staging'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STAGING }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STAGING }}
          K8S_SECRET_ALLOWED_HOSTS: "*"
          K8S_SECRET_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY_STAGING }}
          K8S_SECRET_SKIP_DATABASE_CHECK: 1
          K8S_SECRET_SENTRY_DSN: ${{ secrets.GH_SENTRY_DSN }}
          K8S_SECRET_SENTRY_ENVIRONMENT: "test"
          K8S_SECRET_DATABASE_URL: ${{ secrets.K8S_SECRET_DATABASE_URL_STAGING }}

      - name: Update GTFS feeds
        uses: City-of-Helsinki/setup-cronjob-action@main
        with:
          name: gtfs-feed-update-cronjob
          image_repository: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
          image_tag: ${{ github.sha }}
          kubeconfig_raw: ${{ env.KUBECONFIG_RAW_STAGING }}
          target_namespace: ${{ secrets.K8S_NAMESPACE_STAGING }}
          secret_name: "project-staging-maritime-maas-secret"
          schedule: "*/30 * * * *" # every 30 mins
          command: "{/bin/sh}"
          args: "{-c,cd /app && python manage.py update_gtfs_feeds}"
          max_duration: 1770 # 29min 30s
